---
image_template_packages:
  - bootc
  - podman
  - skopeo
  - git

image_template_trust_ca_src: ""
image_template_trust_ca_dest: /etc/pki/ca-trust/source/anchors/platform-ca.crt

image_template_registry_auth_src: ""
image_template_registry_auth_dest: /etc/ostree/auth.json

image_template_apply_bootc: false
image_template_bootc_image: ""
image_template_bootc_transport: registry
image_template_bootc_retain: true
image_template_reboot_after_switch: false

image_template_prepare_for_template: false
image_template_clean_cloud_init: true
image_template_clean_ssh_host_keys: true
image_template_clean_package_cache: true
