---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart squid
  ansible.builtin.service:
    name: squid
    state: restarted

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
